### ISSUE TITLE
knife discoverer barfs if some nodes don't have ip

### ISSUE THREAD

**Issue by abesto** [abesto/easyssh#17]
```
panic: interface conversion: interface is nil, not string [recovered]
    panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
main.func·001()
    /Users/abesto/playground/go/src/github.com/abesto/easyssh/easyssh.go:34 +0x111
github.com/abesto/easyssh/discoverers.(*knifeSearch).Discover(0x2082da780, 0x7fff5fbfeda4, 0x15, 0x0, 0x0, 0x0)
    /Users/abesto/playground/go/src/github.com/abesto/easyssh/discoverers/discoverers.go:115 +0xb8c
github.com/abesto/easyssh/discoverers.(*firstMatching).Discover(0x2082c66c0, 0x7fff5fbfeda4, 0x15, 0x0, 0x0, 0x0)
    /Users/abesto/playground/go/src/github.com/abesto/easyssh/discoverers/discoverers.go:138 +0x1f2
main.main()
    /Users/abesto/playground/go/src/github.com/abesto/easyssh/easyssh.go:83 +0x809
```

**Comment by abesto** [comment]
Along later commits this morphed into `2015-11-27 20:04:53.415 INFO Targets: [%!s(PANIC=Target host cannot be empty)]`
