### ISSUE TITLE
Improve error message when filter/executor/discoverer definition has errors

### ISSUE THREAD

**Issue by abesto** [abesto/easyssh#6]
The worst case is:

``` sh
smartssh -d '(' foo
panic: Unreachable.

goroutine 1 [running]:
bitbucket.org/shanehanna/sexp.unmarshal(0x2082d4190, 0x0, 0x0, 0x0, 0x0)
    /Users/abesto/playground/go/src/bitbucket.org/shanehanna/sexp/parser.go:45 +0x4d4
bitbucket.org/shanehanna/sexp.Unmarshal(0x2082d0460, 0x1, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/abesto/playground/go/src/bitbucket.org/shanehanna/sexp/parser.go:18 +0x89
github.com/abesto/smartssh/from_sexp.MakeFromString(0x7fff5fbfed9c, 0x1, 0x1caec8, 0x0, 0x0)
    /Users/abesto/playground/go/src/github.com/abesto/smartssh/from_sexp/from_sexp.go:10 +0x72
github.com/abesto/smartssh/discoverers.Make(0x7fff5fbfed9c, 0x1, 0x0, 0x0)
    /Users/abesto/playground/go/src/github.com/abesto/smartssh/discoverers/discoverers.go:15 +0x50
main.main()
    /Users/abesto/playground/go/src/github.com/abesto/smartssh/smartssh.go:66 +0x6f1
```

**Comment by abesto** [comment]
The worst case is:

```sh
smartssh -d '(' foo
panic: Unreachable.

goroutine 1 [running]:
bitbucket.org/shanehanna/sexp.unmarshal(0x2082d4190, 0x0, 0x0, 0x0, 0x0)
	/Users/abesto/playground/go/src/bitbucket.org/shanehanna/sexp/parser.go:45 +0x4d4
bitbucket.org/shanehanna/sexp.Unmarshal(0x2082d0460, 0x1, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/abesto/playground/go/src/bitbucket.org/shanehanna/sexp/parser.go:18 +0x89
github.com/abesto/smartssh/from_sexp.MakeFromString(0x7fff5fbfed9c, 0x1, 0x1caec8, 0x0, 0x0)
	/Users/abesto/playground/go/src/github.com/abesto/smartssh/from_sexp/from_sexp.go:10 +0x72
github.com/abesto/smartssh/discoverers.Make(0x7fff5fbfed9c, 0x1, 0x0, 0x0)
	/Users/abesto/playground/go/src/github.com/abesto/smartssh/discoverers/discoverers.go:15 +0x50
main.main()
	/Users/abesto/playground/go/src/github.com/abesto/smartssh/smartssh.go:66 +0x6f1

**Comment by abesto** [comment]
The current S-Exp parser is `bitbucket.org/shanehanna/sexp`. The branch https://github.com/abesto/easyssh/tree/sexp/eadmund-sexprs tries out `github.com/eadmund/sexprs`, but that also barfs on `(`. The epic continues.

**Comment by abesto** [comment]
Fixed for some of the major cases, paved the way for fixing anything else:
- https://github.com/abesto/easyssh/commit/0e33241d30ebf35dedba86c8ebfc9c0e6123d1a2
- https://github.com/abesto/easyssh/commit/b6e60be17db053f9df92c25f41570811e13eff27
